import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Plaza du dollar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />
      </head>
      <body
        className={`${publicSans.className} antialiased`}
      >
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
